Repository wecode-bootcamp-korea/21-Westagram-backend, pull requests merged in 2021-06, with the labels that each got.

#35 [김경천]Mission 2: 회원가입 엔드포인트완료.
  students/kyoungcheon/user/migrations/0001_initial.py
  students/kyoungcheon/user/migrations/0002_auto_20210528_0828.py
  students/kyoungcheon/user/migrations/0003_alter_member_nickname.py
  students/kyoungcheon/user/migrations/0004_alter_member_phone.py
  students/kyoungcheon/user/migrations/0005_auto_20210528_1211.py
  students/kyoungcheon/user/models.py
  students/kyoungcheon/user/urls.py
  students/kyoungcheon/user/views.py
  students/kyoungcheon/westargram/settings.py
  students/kyoungcheon/westargram/urls.py
Labels: Status: Accepted, 필수 구현 사항

#36 [박준영]Mission 2:회원가입 엔드포인트완료
  students/junyeong/user/migrations/0001_initial.py
  students/junyeong/user/migrations/0002_alter_signup_number.py
  students/junyeong/user/migrations/0003_auto_20210528_0353.py
  students/junyeong/user/migrations/0004_auto_20210528_0436.py
  students/junyeong/user/migrations/0005_alter_signup_password.py
  students/junyeong/user/migrations/0006_alter_signup_password.py
  students/junyeong/user/migrations/0007_alter_signup_password.py
  students/junyeong/user/migrations/0008_auto_20210528_0921.py
  students/junyeong/user/migrations/0009_auto_20210528_1006.py
  students/junyeong/user/migrations/0010_auto_20210528_1139.py
  students/junyeong/user/migrations/0011_auto_20210528_1204.py
  students/junyeong/user/migrations/0012_auto_20210528_1231.py
  students/junyeong/user/migrations/0013_auto_20210531_0707.py
  students/junyeong/user/migrations/0014_auto_20210531_0857.py
  students/junyeong/user/models.py
  students/junyeong/user/urls.py
  students/junyeong/user/views.py
  students/junyeong/westargram/urls.py
Labels: Status: Accepted, 필수 구현 사항

#37 [최승리] Mission2: 회원가입 엔드포인트 완료
  students/seungri/requirements.txt
  students/seungri/user/migrations/0001_initial.py
  students/seungri/user/migrations/0002_auto_20210528_0436.py
  students/seungri/user/migrations/0003_alter_user_table.py
  students/seungri/user/models.py
  students/seungri/user/urls.py
  students/seungri/user/views.py
  students/seungri/westagram/settings.py
  students/seungri/westagram/urls.py
Labels: Status: Accepted, 필수 구현 사항

#42 [송준] [Mission 2] 회원가입 엔드포인트 완료
  students/junsong/user/migrations/0001_initial.py
  students/junsong/user/migrations/0002_alter_user_contact.py
  students/junsong/user/migrations/0003_auto_20210529_0636.py
  students/junsong/user/models.py
  students/junsong/user/urls.py
  students/junsong/user/views.py
  students/junsong/westargram/urls.py
Labels: Status: 리뷰 요청, 필수 구현 사항

#43 [한성봉] mission2: 회원가입 엔드포인트 완료
  students/seongbong/user/migrations/0001_initial.py
  students/seongbong/user/migrations/0002_auto_20210528_0625.py
  students/seongbong/user/migrations/0003_alter_user_password.py
  students/seongbong/user/migrations/0004_auto_20210528_0738.py
  students/seongbong/user/models.py
  students/seongbong/user/urls.py
  students/seongbong/user/views.py
  students/seongbong/westagram/settings.py
  students/seongbong/westagram/urls.py
Labels: Status: 리뷰 요청, Status: 수정 요청, 필수 구현 사항

#44 [범승원] Mission 2: 회원가입 엔드포인트
  students/seungwonburm/users/apps.py
  students/seungwonburm/users/migrations/0001_initial.py
  students/seungwonburm/users/migrations/0002_alter_account_table.py
  students/seungwonburm/users/migrations/0003_alter_account_password.py
  students/seungwonburm/users/models.py
  students/seungwonburm/users/urls.py
  students/seungwonburm/users/views.py
  students/seungwonburm/westagram/settings.py
  students/seungwonburm/westagram/urls.py
Labels: Status: 리뷰 요청, 필수 구현 사항

#45 [배찬영] Mission 2 : 회원가입뷰 작성
  students/chanyoungbae/user/migrations/0001_initial.py
  students/chanyoungbae/user/migrations/0002_alter_user_email.py
  students/chanyoungbae/user/migrations/0003_auto_20210531_0652.py
  students/chanyoungbae/user/models.py
  students/chanyoungbae/user/urls.py
  students/chanyoungbae/user/views.py
  students/chanyoungbae/westargram/settings.py
  students/chanyoungbae/westargram/urls.py
Labels: Status: 리뷰 요청, 필수 구현 사항

#47 [현상협] Mission 2 : 회원가입 기능 구현
  students/sanghyub/user/migrations/0001_initial.py
  students/sanghyub/user/models.py
  students/sanghyub/user/urls.py
  students/sanghyub/user/views.py
  students/sanghyub/westargram/urls.py
Labels: Status: 리뷰 요청, Status: 수정 요청, 필수 구현 사항

#48 [유병건] Mission 3 : 로그인 기능 추가
  students/byunggun/user/migrations/0001_initial.py
  students/byunggun/user/models.py
  students/byunggun/user/urls.py
  students/byunggun/user/views.py
  students/byunggun/westagram/settings.py
  students/byunggun/westagram/urls.py
Labels: Status: 리뷰 요청, 필수 구현 사항

#49 [박창현]Mission 2 : 회원가입뷰 작성
  students/chaghyunpark/userapp/__init__.py
  students/chaghyunpark/userapp/admin.py
  students/chaghyunpark/userapp/apps.py
  students/chaghyunpark/userapp/migrations/0001_initial.py
  students/chaghyunpark/userapp/migrations/__init__.py
  students/chaghyunpark/userapp/models.py
  students/chaghyunpark/userapp/tests.py
  students/chaghyunpark/userapp/urls.py
  students/chaghyunpark/userapp/views.py
  students/chaghyunpark/westagram/settings.py
  students/chaghyunpark/westagram/urls.py
Labels: Status: 리뷰 요청, 필수 구현 사항

#50 [이정민] Mission 2 : 회원가입 기능 구현
  students/jungmin/users/__init__.py
  students/jungmin/users/admin.py
  students/jungmin/users/apps.py
  students/jungmin/users/migrations/0001_initial.py
  students/jungmin/users/migrations/0002_alter_user_user_email.py
  students/jungmin/users/migrations/0003_auto_20210528_0717.py
  students/jungmin/users/migrations/0004_rename_passward_user_password.py
  students/jungmin/users/migrations/0005_auto_20210528_1114.py
  students/jungmin/users/migrations/0006_auto_20210528_1132.py
  students/jungmin/users/migrations/0007_alter_user_user_email.py
  students/jungmin/users/migrations/0008_auto_20210531_0748.py
  students/jungmin/users/migrations/__init__.py
  students/jungmin/users/models.py
  students/jungmin/users/tests.py
  students/jungmin/users/urls.py
  students/jungmin/users/views.py
  students/jungmin/westargram/settings.py
  students/jungmin/westargram/urls.py
Labels: Status: 리뷰 요청, 필수 구현 사항

#51 [김민규] Misson 2 회원가입 엔드포인트 완료 / 수정 완료
  students/mingyu/user/apps.py
  students/mingyu/user/migrations/0001_initial.py
  students/mingyu/user/migrations/0002_auto_20210528_1030.py
  students/mingyu/user/migrations/0003_alter_user_phone_number.py
  students/mingyu/user/models.py
  students/mingyu/user/urls.py
  students/mingyu/user/views.py
  students/mingyu/westagram/urls.py
Labels: Status: 리뷰 요청, 필수 구현 사항

#57 [황복실] Mission 2: 회원가입 엔드포인트 완료 / 수정완료
  students/boksil/user/migrations/__init__.py
  students/boksil/user/models.py
  students/boksil/users/__init__.py
  students/boksil/users/admin.py
  students/boksil/users/apps.py
  students/boksil/users/migrations/0001_initial.py
  students/boksil/users/migrations/0002_auto_20210528_0729.py
  students/boksil/users/migrations/0003_auto_20210531_0659.py
  students/boksil/users/migrations/__init__.py
  students/boksil/users/models.py
  students/boksil/users/tests.py
  students/boksil/users/urls.py
  students/boksil/users/views.py
  students/boksil/westagram/settings.py
  students/boksil/westagram/urls.py
Labels: Status: 리뷰 요청, 필수 구현 사항

#53 [박지우] Mission2 : 회원가입 엔드포인트 완료
  students/jiu/user/__init__.py
  students/jiu/user/admin.py
  students/jiu/user/apps.py
  students/jiu/user/migrations/0001_initial.py
  students/jiu/user/migrations/__init__.py
  students/jiu/user/models.py
  students/jiu/user/tests.py
  students/jiu/user/urls.py
  students/jiu/user/views.py
  students/jiu/westagram/settings.py
  students/jiu/westagram/urls.py
Labels: Status: Accepted, 필수 구현 사항

#52 [김성규] Mission 2: 회원가입 엔드포인트 완료
  students/sungkyu/user/migrations/0001_initial.py
  students/sungkyu/user/migrations/0002_auto_20210531_0740.py
  students/sungkyu/user/models.py
  students/sungkyu/user/urls.py
  students/sungkyu/user/views.py
  students/sungkyu/westagram/urls.py
Labels: Status: 수정 요청, 필수 구현 사항

#54 [이아란] Mission:2 회원가입 엔드포인트 완료
  students/aranlee/.gitignore
  students/aranlee/user/admin.py
  students/aranlee/user/migrations/0001_initial.py
  students/aranlee/user/models.py
  students/aranlee/user/tests.py
  students/aranlee/user/urls.py
  students/aranlee/user/views.py
  students/aranlee/westagram/settings.py
  students/aranlee/westagram/urls.py
Labels: Status: 리뷰 요청, 필수 구현 사항

#59 [정효진] Mission 3: 로그인 엔드포인트 완료
  students/hyojin/user/migrations/0006_auto_20210531_1035.py
  students/hyojin/user/models.py
  students/hyojin/user/urls.py
  students/hyojin/user/views.py
Labels: Status: 리뷰 요청, 필수 구현 사항

#58 [김태우] Misssion3 로그인 엔드포인트 구현 완료
  students/taewookim/users/migrations/0005_alter_user_password.py
  students/taewookim/users/migrations/0006_alter_user_password.py
  students/taewookim/users/models.py
  students/taewookim/users/urls.py
  students/taewookim/users/views.py
  students/taewookim/westagram/settings.py
Labels: Status: Accepted, 필수 구현 사항

#65 [장동국]Mission2: 회원가입 엔드포인트 완료
  students/dongguk/.vscode/settings.json
  students/dongguk/user/models.py
  students/dongguk/user/views.py
  students/dongguk/users/__init__.py
  students/dongguk/users/admin.py
  students/dongguk/users/apps.py
  students/dongguk/users/migrations/0001_initial.py
  students/dongguk/users/migrations/__init__.py
  students/dongguk/users/models.py
  students/dongguk/users/tests.py
  students/dongguk/users/urls.py
  students/dongguk/users/views.py
  students/dongguk/westagram/settings.py
  students/dongguk/westagram/urls.py
Labels: Status: 리뷰 요청, 필수 구현 사항

#63 [박준영]Mission3: 로그인 엔드포인트 수정완료
  students/junyeong/user/urls.py
  students/junyeong/user/views.py
  students/junyeong/westargram/settings.py
Labels: Status: 리뷰 요청, 필수 구현 사항

#64 [박창현] Mission 3 로그인 엔드포인트
  students/chaghyunpark/userapp/migrations/0002_auto_20210531_1635.py
  students/chaghyunpark/userapp/models.py
  students/chaghyunpark/userapp/urls.py
  students/chaghyunpark/userapp/views.py
  students/chaghyunpark/westagram/settings.py
Labels: Status: 리뷰 요청, 필수 구현 사항

#62 [송준] Mission 3: 로그인 엔드포인트 완료
  students/junsong/user/migrations/0004_alter_user_password.py
  students/junsong/user/models.py
  students/junsong/user/urls.py
  students/junsong/user/views.py
Labels: Status: Accepted, 필수 구현 사항

#66 [배찬영] Mission 3 : 로그인 엔드포인트
  students/chanyoungbae/user/urls.py
  students/chanyoungbae/user/views.py
  students/chanyoungbae/westargram/urls.py
Labels: Status: 리뷰 요청, 필수 구현 사항

#67 [범승원] Mission 3 : 로그인 엔드포인트 구현완료
  students/seungwonburm/users/models.py
  students/seungwonburm/users/urls.py
  students/seungwonburm/users/views.py
  students/seungwonburm/westagram/urls.py
Labels: Status: 리뷰 요청, 필수 구현 사항

#68 [최승리] Mission3 : 로그인 엔드포인트 완료
  students/seungri/postings/__init__.py
  students/seungri/postings/admin.py
  students/seungri/postings/apps.py
  students/seungri/postings/migrations/__init__.py
  students/seungri/postings/models.py
  students/seungri/postings/tests.py
  students/seungri/postings/urls.py
  students/seungri/postings/views.py
  students/seungri/user/migrations/0004_alter_user_password.py
  students/seungri/user/models.py
  students/seungri/user/urls.py
  students/seungri/user/views.py
  students/seungri/westagram/settings.py
  students/seungri/westagram/urls.py
Labels: Status: 리뷰 요청, 필수 구현 사항

#71 [김경천]Mission3 :로그인 엔드포인트 완료
  students/kyoungcheon/.vscode/settings.json
  students/kyoungcheon/user/urls.py
  students/kyoungcheon/user/views.py
Labels: Status: 리뷰 요청, 필수 구현 사항

#72 [김민규] Misson 3 : 로그인 엔드포인트 완료
  students/mingyu/user/urls.py
  students/mingyu/user/views.py
Labels: Status: Accepted, 필수 구현 사항

#79 [이정민] Mission: 3 로그인 구현 완료
  students/jungmin/.vscode/settings.json
  students/jungmin/users/migrations/0009_alter_user_password.py
  students/jungmin/users/models.py
  students/jungmin/users/urls.py
  students/jungmin/users/views.py
Labels: Status: Accepted, 필수 구현 사항

#74 [한성봉] Mission3: 로그인 엔드포인트 완료
  students/seongbong/user/urls.py
  students/seongbong/user/views.py
  students/seongbong/westagram/settings.py
Labels: Status: Accepted, 필수 구현 사항

#77 [황복실] Mission 3: 로그인 엔드포인트 완료 / 수정완료
  students/boksil/.vscode/settings.json
  students/boksil/users/migrations/0004_alter_user_mobile.py
  students/boksil/users/migrations/0005_alter_user_nickname.py
  students/boksil/users/migrations/0006_auto_20210602_0702.py
  students/boksil/users/migrations/0007_auto_20210602_0729.py
  students/boksil/users/migrations/0008_auto_20210602_0733.py
  students/boksil/users/models.py
  students/boksil/users/urls.py
  students/boksil/users/views.py
  students/boksil/westagram/settings.py
  students/boksil/westagram/urls.py
Labels: Status: Accepted, 필수 구현 사항

#70 [현상협] Mission 3 : 로그인 엔드포인트 완료
  students/sanghyub/.gitignore
  students/sanghyub/posting/__init__.py
  students/sanghyub/posting/admin.py
  students/sanghyub/posting/apps.py
  students/sanghyub/posting/migrations/0001_initial.py
  students/sanghyub/posting/migrations/0002_auto_20210602_2019.py
  students/sanghyub/posting/migrations/0003_alter_image_table.py
  students/sanghyub/posting/migrations/__init__.py
  students/sanghyub/posting/models.py
  students/sanghyub/posting/tests.py
  students/sanghyub/posting/urls.py
  students/sanghyub/posting/views.py
  students/sanghyub/user/models.py
  students/sanghyub/user/urls.py
  students/sanghyub/user/views.py
  students/sanghyub/westargram/settings.py
  students/sanghyub/westargram/urls.py
Labels: Status: 리뷰 요청, 필수 구현 사항

#83 [장동국]Mission3: 로그인 엔드포인트 완료
  students/dongguk/users/urls.py
  students/dongguk/users/views.py
Labels: Status: Accepted, 필수 구현 사항

#73 [김정연]Mission3: 로그인 엔드포인트 완료
  students/jyeon/.vscode/settings.json
  students/jyeon/jyeon/settings.py
  students/jyeon/jyeon/urls.py
  students/jyeon/posting/__init__.py
  students/jyeon/posting/admin.py
  students/jyeon/posting/apps.py
  students/jyeon/posting/migrations/0001_initial.py
  students/jyeon/posting/migrations/0002_auto_20210530_1502.py
  students/jyeon/posting/migrations/0003_auto_20210530_1515.py
  students/jyeon/posting/migrations/0004_auto_20210530_1515.py
  students/jyeon/posting/migrations/0005_auto_20210531_0818.py
  students/jyeon/posting/migrations/0006_auto_20210601_1616.py
  students/jyeon/posting/migrations/0007_auto_20210601_2036.py
  students/jyeon/posting/migrations/0008_auto_20210601_2041.py
  students/jyeon/posting/migrations/0009_auto_20210601_2042.py
  students/jyeon/posting/migrations/__init__.py
  students/jyeon/posting/models.py
  students/jyeon/posting/tests.py
  students/jyeon/posting/urls.py
  students/jyeon/posting/utils.py
  students/jyeon/posting/views.py
  students/jyeon/user/migrations/0001_initial.py
  students/jyeon/user/migrations/0002_alter_user_phone_number.py
  students/jyeon/user/migrations/0003_auto_20210531_0839.py
  students/jyeon/user/migrations/0004_auto_20210601_1616.py
  students/jyeon/user/models.py
  students/jyeon/user/urls.py
  students/jyeon/user/views.py
Labels: Status: 리뷰 요청, 필수 구현 사항
